export const animationData = {
  v: '5.7.4',
  fr: 30,
  ip: 0,
  op: 31,
  w: 1920,
  h: 1080,
  nm: '2D_point_test',
  ddd: 0,
  assets: [],
  layers: [
    {
      ddd: 0,
      ind: 1,
      ty: 4,
      nm: 'point_blue',
      sr: 1,
      ks: {
        o: { a: 0, k: 100, ix: 11 },
        r: { a: 0, k: 0, ix: 10 },
        p: {
          s: true,
          x: {
            a: 1,
            k: [
              {
                i: { x: [0.833], y: [0.833] },
                o: { x: [0.167], y: [0.167] },
                t: 0,
                s: [500],
              },
              {
                i: { x: [0.833], y: [0.833] },
                o: { x: [0.167], y: [0.167] },
                t: 15,
                s: [1400],
              },
              { t: 30, s: [500] },
            ],
            ix: 3,
          },
          y: {
            a: 1,
            k: [
              {
                i: { x: [0.833], y: [0.833] },
                o: { x: [0.167], y: [0.167] },
                t: 0,
                s: [540],
              },
              {
                i: { x: [0.833], y: [0.833] },
                o: { x: [0.167], y: [0.167] },
                t: 15,
                s: [540],
              },
              { t: 30, s: [540] },
            ],
            ix: 4,
          },
        },
        a: { a: 0, k: [0, 0, 0], ix: 1, l: 2 },
        s: { a: 0, k: [100, 100, 100], ix: 6, l: 2 },
      },
      ao: 0,
      shapes: [
        {
          d: 1,
          ty: 'el',
          s: { a: 0, k: [50, 50], ix: 2 },
          p: { a: 0, k: [0, 0], ix: 3 },
          nm: '楕円形パス 1',
          mn: 'ADBE Vector Shape - Ellipse',
          hd: false,
        },
        {
          ty: 'fl',
          c: { a: 0, k: [0, 0.094117484987, 1, 1], ix: 4 },
          o: { a: 0, k: 100, ix: 5 },
          r: 1,
          bm: 0,
          nm: '塗り 1',
          mn: 'ADBE Vector Graphic - Fill',
          hd: false,
        },
      ],
      ip: 0,
      op: 300,
      st: 0,
      bm: 0,
    },
    {
      ddd: 0,
      ind: 2,
      ty: 4,
      nm: 'square_red',
      sr: 1,
      ks: {
        o: { a: 0, k: 100, ix: 11 },
        r: { a: 0, k: 0, ix: 10 },
        p: {
          s: true,
          x: {
            a: 0,
            k: 50,
            ix: 3,
            x: "var $bm_rt;\n$bm_rt = $bm_sum(960, $bm_div($bm_sub(thisComp.layer('point_blue').transform.xPosition, 960), 2));",
          },
          y: {
            a: 0,
            k: -354,
            ix: 4,
            x: "var $bm_rt;\n$bm_rt = $bm_sum(540, $bm_div($bm_sub(thisComp.layer('point_blue').transform.yPosition, 540), 2));",
          },
        },
        a: { a: 0, k: [0, 0, 0], ix: 1, l: 2 },
        s: { a: 0, k: [100, 100, 100], ix: 6, l: 2 },
      },
      ao: 0,
      shapes: [
        {
          ty: 'rc',
          d: 1,
          s: { a: 0, k: [500, 500], ix: 2 },
          p: { a: 0, k: [0, 0], ix: 3 },
          r: { a: 0, k: 0, ix: 4 },
          nm: '長方形パス 1',
          mn: 'ADBE Vector Shape - Rect',
          hd: false,
        },
        {
          ty: 'fl',
          c: { a: 0, k: [1, 0, 0, 1], ix: 4 },
          o: { a: 0, k: 100, ix: 5 },
          r: 1,
          bm: 0,
          nm: '塗り 1',
          mn: 'ADBE Vector Graphic - Fill',
          hd: false,
        },
      ],
      ip: 0,
      op: 300,
      st: 0,
      bm: 0,
    },
  ],
  markers: [],
};
